---
# Experiment description
name: Go No-Go Interruption
description: Testing Go No-Go Interruption task
experimenter:
    name: Tyler Lee
    email: &def_email "siriuslee305@gmail.com"

# Experiment properties
subject: Test
panel_name: Thing2
light_schedule:
    - !!python/tuple ["05:00", "22:00"]
idle_poll_interval: 60.0

# Session details
num_sessions: 1
session_schedule:
    - !!python/tuple ["05:00", "22:00"]
shape: false

# Behavior properties
reward_value: 10.0

# File paths
experiment_path: "/home/tlee/Data/pecking_test"

# Block properties
blocks:
    # Block number 1
    - conditions:
        # Rewarded stimuli
        rewarded:
            file_path: "/auto/tdrive/tlee/operant/stimuli/trial_run_day1/reward"
            weight: 0.2
        # Unrewarded stimuli
        unrewarded:
            file_path: "/auto/tdrive/tlee/operant/stimuli/trial_run_day1/nonreward"
            weight: 0.8
      # Reinforcement schedule
      reinforcement: continuous
      # Trial Queue
      queue: random
      queue_parameters: {}
      max_trials: 20
# Block Queue
block_queue: block
block_queue_parameters: {}

# Log handler setup
# Possible values are file, email
log_handlers:
    # Logging to file
    file:
        filename: ""
        level: !!python/name:logging.DEBUG
    email:
        mailhost: localhost
        toaddrs:
            - *def_email
        fromaddr: "Pecking <pecking@fet.berkeley.edu>"
        subject: "pyoperant notice"
        credentials: none
        secure: none
        level: !!python/name:logging.ERROR
...
