---
# You should probably only have to change these values
experimenter:
    name: Tyler Lee
    email: &def_email "siriuslee305@gmail.com"

# Experiment properties
subject_name: &subject TestSubject

# Stimulus directory
stim_directory: &stims "/Users/tylerlee/testing/stimuli"

# Log key data during polling
log_polling: true
log_polling_file: "keydata.log"

# These values should probably be left unchanged unless you know what you're doing.

# Experiment description
name: Go No-Go Interruption
description: Runs a Go No-Go Interruption task

# Subject properties
subject: !!python/object/apply:pyoperant.subjects.Subject
    kwds:
        name: *subject
        datastore: csv

# Panel
panel: !!python/object/apply:pyoperant.tlab.local_tlab.Mac
    kwds: {}

# Experiment properties
light_schedule:
    - !!python/tuple ["05:00", "23:59"]
idle_poll_interval: 60.0

# File paths
experiment_path: "/Users/tylerlee/testing/data/" # This is the root directory and will be appended with subject and date

# Stimulus conditions
conditions:
    - &rewarded !!python/object/apply:pyoperant.behavior.go_no_go_interrupt.RewardedCondition
      kwds:
          file_path: !!python/object/apply:os.path.join [*stims, "reward"]
    - &unrewarded !!python/object/apply:pyoperant.behavior.go_no_go_interrupt.UnrewardedCondition
      kwds:
          file_path: !!python/object/apply:os.path.join [*stims, "nonreward"]

# Queues
queues:
    - &random !!python/name:pyoperant.queues.random_queue
    - &block !!python/name:pyoperant.queues.block_queue

# Reinforcement schedules
reinforcement:
    - &continuous !!python/object/apply:pyoperant.reinf.ContinuousReinforcement
      kwds: {}

# Block properties
blocks:
    # Block number 1
    - !!python/object/apply:pyoperant.blocks.Block
        kwds:
            conditions:
                # Rewarded stimuli
                - *rewarded
                # Unrewarded stimuli
                - *unrewarded
            weights:
                - 0.2
                - 0.8
            queue: *random
            queue_parameters:
                max_items: none
            reinforcement: *continuous

block_queue: *block
block_queue_parameters: {}
block_weights: none

# Session details
num_sessions: 1
session_schedule:
    - !!python/tuple ["05:00", "23:59"]
shape: false

reward_value: 12.0

# Log handler setup
# Possible values are stream, file, email
log_handlers:
    # stream's only option is level. Overrides "debug" parameter for logging
    stream:
        level: !!python/name:logging.DEBUG
    # file takes options of
    # filename: a file under experiment_path
    # level: a python logging level, written as "!!python/name:logging.LEVEL"
    file:
        filename: "experiment.log"
        level: !!python/name:logging.DEBUG
    # email takes options of
    # mailhost: where the email is sent from
    # toaddrs: a list of addresses to send to
    # fromaddr: the address to send from
    # subject: The subject line
    # credentials: not sure
    # secure: not sure
    # level: a python logging level, written as "!!python/name:logging.LEVEL"
    # email:
    #     mailhost: localhost
    #     toaddrs:
    #         - *def_email
    #     fromaddr: "Pyoperant <pyoperant@someemail.com"
    #     subject: "pyoperant notice"
    #     credentials: none
    #     secure: none
    #     level: !!python/name:logging.ERROR
...
